version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-5259
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - newgeppettoapplicationdemo005_5259-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-5259
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-5259
    container_name: authproxy-5259
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-5259
    container_name: securitymanager-5259
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-5259
    container_name: camundasvc-5259
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-5259
    container_name: apigateway-5259
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - users
      - projects
      - manager
      - lead



  users: 
    build: ../../../application/services/custom_services/users
    image: users-5259
    container_name: users-5259
    ports: 
      - 8005:8005
    env_file: .env
    depends_on:
      - mongo

  projects: 
    build: ../../../application/services/custom_services/projects
    image: projects-5259
    container_name: projects-5259
    ports: 
      - 8006:8006
    env_file: .env
    depends_on:
      - mongo

  manager: 
    build: ../../../application/services/custom_services/manager
    image: manager-5259
    container_name: manager-5259
    ports: 
      - 8007:8007
    env_file: .env
    depends_on:
      - mongo

  lead: 
    build: ../../../application/services/custom_services/lead
    image: lead-5259
    container_name: lead-5259
    ports: 
      - 8008:8008
    env_file: .env
    depends_on:
      - mongo


volumes:
  newgeppettoapplicationdemo005_5259-volume:
    driver: local
